---
- name: "Deploy rancher chart"
  frantchenco.helm_wrapper.install:
    name: "{{ helm_rancher_name }}"
    chart_repo_url: "{{ helm_rancher_chart_repo_url }}"
    chart_version: "{{ helm_rancher_chart_version }}"
    chart_ref: "{{ helm_rancher_chart_ref }}"
    release_namespace: "{{ helm_rancher_release_namespace }}"
    create_namespace: "{{ helm_rancher_create_namespace }}"
    values: "{{ helm_rancher_values | to_json }}"
    values_files: "{{ helm_rancher_values_files }}"
    wait: "{{ helm_rancher_wait }}"
    disable_hook: "{{ helm_rancher_disable_hook }}"
    force: "{{ helm_rancher_force }}"
    atomic: "{{ helm_rancher_atomic }}"
    skip_crds: "{{ helm_rancher_skip_crds }}"
    update_repo_cache: "{{ helm_rancher_update_repo_cache }}"
    binary_path: "{{ helm_rancher_binary_path }}"
    context: "{{ helm_rancher_context }}"
    kubeconfig: "{{ helm_rancher_kubeconfig }}"
    validate_certs: "{{ helm_rancher_validate_certs }}"

- name: Patch rancher ingress
  kubernetes.core.k8s_json_patch:
    api_version: networking.k8s.io/v1
    kind: Ingress
    namespace: cattle-system
    name: rancher
    patch:
      - op: add
        path: /spec/ingressClassName
        value: nginx
